### PR TITLE
fix(operator): Resources should be synced after k8sgptConfig  CR update

### LINKED ISSUE #173: [Bug]: k8sgpt-deployment is not synchronized, after k8sgptConfig update
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.8

### Kubernetes Version

v1.25.6

### Host OS and its Version

ubuntu

### Steps to reproduce

1. create a k8sGPT CR with a invalid baseUrl, say 
```bash
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
  namespace: default
spec:
  ai:
    enabled: true
    model: ggml-gpt4all-j
    backend: localai
    baseUrl: http://local-ai.local-ai.svc.cluster.local:8080/v1
  noCache: false
  version: v0.3.8
EOF
```
2. check operator log

image

3. fix baseUrl to `http://local-ai.local-ai.svc.cluster.local/v1`
image

4. check operator & deployment logs
> operator log 
image

> deployment log
image

### Expected behaviour

k8sGPT-deployment should use the latest configuration after the K8sGPT CR changes

### Actual behaviour

The k8sGPT-deployment configuration has not been updated with the latest configuration after the K8sGPT CR changes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by fyuan1316**
Closes #173 

## 📑 Description

Add support for k8sgpt deployment and Service configuration updates
## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

File: controllers/k8sgpt_controller.go [hunk 1]
```diff
@@ -125,13 +125,14 @@ func (r *K8sGPTReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 	deployment := v1.Deployment{}
 	err = r.Get(ctx, client.ObjectKey{Namespace: k8sgptConfig.Namespace,
 		Name: "k8sgpt-deployment"}, &deployment)
+	if client.IgnoreNotFound(err) != nil {
+		k8sgptReconcileErrorCount.Inc()
+		return r.finishReconcile(err, false)
+	}
+	err = resources.Sync(ctx, r.Client, *k8sgptConfig, resources.SyncOp)
```
Comment (AlexsJones) [inline controllers/k8sgpt_controller.go:132]: Sorry it took a while to look at this - why don't we check for version change before we force an entire sync?

Comment (fyuan1316) [reply controllers/k8sgpt_controller.go:132]: thans for the review.

Because here k8sgptConfig carries the latest user expected configuration. If we check for changes in subresource configurations, we need to calculate the expected configurations for deployments, services, etc. and compare them with the existing configurations. Then synchronize as needed. 

Personally, I think the underlying use is a caching client, and while it may look like full synchronization here, the comparison of expected and existing configurations is done in `controllerutil.CreateOrPatch` without much additional overhead. So I think we can keep the original resources.Sync logic intact.

**Comment by arbreezy** [comment]
I will have a look over the weekend @fyuan1316 , thanks for the contribution and apologies for the radio silence :)

**Comment by AlexsJones** [comment]
This looks good to me - tested it out. My only worry is the constant load this puts on the API server, but I imagine its pretty trivial. 
WDYT @arbreezy @fyuan1316 ?

**Review by AlexsJones — DISMISSED** [review]

**Comment by fyuan1316** [comment]
> This looks good to me - tested it out. My only worry is the constant load this puts on the API server, but I imagine its pretty trivial. WDYT @arbreezy @fyuan1316 ?

Yeah, I think the overheads are minimal.

@arbreezy @AlexsJones 
I've noticed that some people have had similar problems. Is it possible to merge the code if this modification works. :smiley:
